### ISSUE TITLE
How to search for a specific server?

### ISSUE THREAD

**Issue by rizalgowandy** [adzimzf/tpot#4]
On this prompt, how to search for a specific server?
Because the list is too long, it's a painful process to look up a server manually.

I was expecting some command like below to filter the server.
```
?digital-subscription or /digital-subscription
```

![Screenshot_2020-12-23_07-11-52](https://user-images.githubusercontent.com/6873609/102944721-2b0b5400-44ee-11eb-91ec-4891c2c7720b.png)

**Comment by adzimzf** [comment]
You can just type the pattern then hit `TAB`
