### ISSUE TITLE
SUPPORT MAC DONG OI

### ISSUE THREAD

**Issue by irftokped** [adzimzf/tpot#6]
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/29912981/107348380-81ae0b00-6af9-11eb-9351-83c2d03a065f.png">

**Comment by adzimzf** [comment]
OTW yah,

**Comment by adzimzf** [comment]
sudah ada yah,
di brew juga sudah bisa 
brew tap adzimzf/tpot
brew install tpot
